server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;
    server_name culturalheritage.coop www.culturalheritage.coop;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
